server:
  port: 8008

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/web3_indexer
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      database: 2  # 为 analytics 使用独立的 DB
  elasticsearch:
    uris: http://localhost:9200
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

# 分析任务配置
analytics:
  schedules:
    token-transfer-stats: "0 */5 * * * ?"  # 每5分钟
    address-ranking: "0 0 */1 * * ?"       # 每小时
    nft-rarity: "0 0 2 * * ?"              # 每天2点
    trend-analysis: "0 */30 * * * ?"       # 每30分钟
  cache:
    ttl: 3600  # 缓存1小时