server:
  port: 8000  # 修正端口配置

spring:
  application:
    name: auth-service  # 添加应用名称，用于Nacos注册
  datasource:
    url: jdbc:mysql://localhost:3307/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # 移除或更新方言配置
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 添加Nacos配置