server:
  port: 8004

spring:
  application:
    name: tx-processor
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml