spring:
  config:
    import:
      - "classpath:blockchain.yml"
  application:
    name: chain-indexer
  datasource:
    url: jdbc:postgresql://localhost:5432/web3_indexer
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
    # HikariCP 连接池配置
    hikari:
      pool-name: BlockchainHikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 5000
      auto-commit: true


# Web3 配置
web3:
  rpc:
    url: https://mainnet.infura.io/v3/your-project-id
  blockchain:
    start-block: 18000000
    batch-size: 100

server:
  port: 8002